# Generated by Django 3.0.8 on 2021-02-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210213_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='signup_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
