# Generated by Django 3.0.8 on 2021-02-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210213_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='application_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
