from django.db import models
# from account.models import organization
# Create your models here.

class LoanApplication(models.Model):
    LOAN_ID = models.IntegerField(null=True ,blank=True)   
    age = models.IntegerField(null=True ,blank=True)
    ed = models.IntegerField(null=True ,blank=True)
    employ = models.IntegerField(null=True ,blank=True)
    address = models.IntegerField(null=True ,blank=True)
    income = models.IntegerField(null=True ,blank=True)
    debtinc = models.FloatField(null=True ,blank=True)
    creddebt = models.FloatField(null=True ,blank=True)
    othdebt = models.FloatField(null=True ,blank=True)
    


class Loan_History(models.Model):
    LOAN_ID = models.IntegerField(null=True ,blank=True)
    NAME_CONTRACT_TYPE = models.CharField(null=True ,blank=True,max_length=70)
    CODE_GENDER = models.CharField(null=True ,blank=True,max_length=70)
    FLAG_OWN_CAR = models.CharField(null=True ,blank=True,max_length=70)
    FLAG_OWN_REALTY = models.CharField(null=True ,blank=True,max_length=70)
    NAME_TYPE_SUITE = models.CharField(null=True ,blank=True,max_length=70)
    NAME_INCOME_TYPE = models.CharField(null=True ,blank=True,max_length=70)
    NAME_EDUCATION_TYPE = models.CharField(null=True ,blank=True,max_length=70)
    NAME_FAMILY_STATUS = models.CharField(null=True ,blank=True,max_length=70)
    NAME_HOUSING_TYPE = models.CharField(null=True ,blank=True,max_length=70)
    OCCUPATION_TYPE = models.CharField(null=True ,blank=True,max_length=70)
    WEEKDAY_APPR_PROCESS_START = models.CharField(null=True ,blank=True,max_length=70)
    ORGANIZATION_TYPE = models.CharField(null=True ,blank=True,max_length=70)
    FONDKAPREMONT_MODE = models.CharField(null=True ,blank=True,max_length=70)
    HOUSETYPE_MODE = models.CharField(null=True ,blank=True,max_length=70)
    WALLSMATERIAL_MODE = models.CharField(null=True ,blank=True,max_length=70)
    EMERGENCYSTATE_MODE = models.CharField(null=True ,blank=True,max_length=70)
    TARGET = models.IntegerField(null=True ,blank=True)
    CNT_CHILDREN = models.IntegerField(null=True ,blank=True)
    AMT_INCOME_TOTAL = models.FloatField(null=True ,blank=True)
    AMT_CREDIT = models.FloatField(null=True ,blank=True)
    AMT_ANNUITY  = models.FloatField(null=True ,blank=True)
    AMT_GOODS_PRICE =models.FloatField(null=True ,blank=True)
    REGION_POPULATION_RELATIVE = models.FloatField(null=True ,blank=True)
    DAYS_BIRTH = models.IntegerField(null=True ,blank=True)
    DAYS_EMPLOYED = models.IntegerField(null=True ,blank=True)
    DAYS_REGISTRATION = models.IntegerField(null=True ,blank=True)
    DAYS_ID_PUBLISH = models.IntegerField(null=True ,blank=True)
    OWN_CAR_AGE = models.FloatField(null=True ,blank=True)
    FLAG_MOBIL = models.IntegerField(null=True ,blank=True)
    FLAG_EMP_PHONE = models.IntegerField(null=True ,blank=True)
    FLAG_WORK_PHONE = models.IntegerField(null=True ,blank=True)
    FLAG_CONT_MOBILE = models.IntegerField(null=True ,blank=True)
    FLAG_PHONE = models.IntegerField(null=True ,blank=True)
    FLAG_EMAIL = models.IntegerField(null=True ,blank=True)
    CNT_FAM_MEMBERS = models.IntegerField(null=True ,blank=True)
    REGION_RATING_CLIENT = models.IntegerField(null=True ,blank=True)
    REGION_RATING_CLIENT_W_CITY = models.IntegerField(null=True ,blank=True)
    HOUR_APPR_PROCESS_START = models.IntegerField(null=True ,blank=True)
    REG_REGION_NOT_LIVE_REGION = models.IntegerField(null=True ,blank=True)
    REG_REGION_NOT_WORK_REGION = models.IntegerField(null=True ,blank=True)
    LIVE_REGION_NOT_WORK_REGION = models.IntegerField(null=True ,blank=True)
    REG_CITY_NOT_LIVE_CITY = models.IntegerField(null=True ,blank=True)
    REG_CITY_NOT_WORK_CITY = models.IntegerField(null=True ,blank=True)
    LIVE_CITY_NOT_WORK_CITY = models.IntegerField(null=True ,blank=True)
    EXT_SOURCE_1  = models.FloatField(null=True ,blank=True)
    EXT_SOURCE_2  = models.FloatField(null=True ,blank=True)
    EXT_SOURCE_3  = models.FloatField(null=True ,blank=True)
    APARTMENTS_AVG  = models.FloatField(null=True ,blank=True)
    BASEMENTAREA_AVG  = models.FloatField(null=True ,blank=True)
    YEARS_BEGINEXPLUATATION_AVG  = models.FloatField(null=True ,blank=True)
    YEARS_BUILD_AVG  = models.FloatField(null=True ,blank=True)
    COMMONAREA_AVG  = models.FloatField(null=True ,blank=True)
    ELEVATORS_AVG  = models.FloatField(null=True ,blank=True)
    ENTRANCES_AVG  = models.FloatField(null=True ,blank=True)
    FLOORSMAX_AVG  = models.FloatField(null=True ,blank=True)
    FLOORSMIN_AVG  = models.FloatField(null=True ,blank=True)
    LANDAREA_AVG  = models.FloatField(null=True ,blank=True)
    LIVINGAPARTMENTS_AVG  = models.FloatField(null=True ,blank=True)
    LIVINGAREA_AVG  = models.FloatField(null=True ,blank=True)
    NONLIVINGAPARTMENTS_AVG  = models.FloatField(null=True ,blank=True)
    NONLIVINGAREA_AVG  = models.FloatField(null=True ,blank=True)
    APARTMENTS_MODE  = models.FloatField(null=True ,blank=True)
    BASEMENTAREA_MODE  = models.FloatField(null=True ,blank=True)
    YEARS_BEGINEXPLUATATION_MODE  = models.FloatField(null=True ,blank=True)
    YEARS_BUILD_MODE  = models.FloatField(null=True ,blank=True)
    COMMONAREA_MODE  = models.FloatField(null=True ,blank=True)
    ELEVATORS_MODE  = models.FloatField(null=True ,blank=True)
    ENTRANCES_MODE  = models.FloatField(null=True ,blank=True)
    FLOORSMAX_MODE  = models.FloatField(null=True ,blank=True)
    FLOORSMIN_MODE  = models.FloatField(null=True ,blank=True)
    LANDAREA_MODE  = models.FloatField(null=True ,blank=True)
    LIVINGAPARTMENTS_MODE  = models.FloatField(null=True ,blank=True)
    LIVINGAREA_MODE  = models.FloatField(null=True ,blank=True)
    NONLIVINGAPARTMENTS_MODE  = models.FloatField(null=True ,blank=True)
    NONLIVINGAREA_MODE  = models.FloatField(null=True ,blank=True)
    APARTMENTS_MEDI  = models.FloatField(null=True ,blank=True)
    BASEMENTAREA_MEDI  = models.FloatField(null=True ,blank=True)
    YEARS_BEGINEXPLUATATION_MEDI  = models.FloatField(null=True ,blank=True)
    YEARS_BUILD_MEDI  = models.FloatField(null=True ,blank=True)
    COMMONAREA_MEDI  = models.FloatField(null=True ,blank=True)
    ELEVATORS_MEDI  = models.FloatField(null=True ,blank=True)
    ENTRANCES_MEDI  = models.FloatField(null=True ,blank=True)
    FLOORSMAX_MEDI  = models.FloatField(null=True ,blank=True)
    FLOORSMIN_MEDI  = models.FloatField(null=True ,blank=True)
    LANDAREA_MEDI  = models.FloatField(null=True ,blank=True)
    LIVINGAPARTMENTS_MEDI  = models.FloatField(null=True ,blank=True)
    LIVINGAREA_MEDI  = models.FloatField(null=True ,blank=True)
    NONLIVINGAPARTMENTS_MEDI  = models.FloatField(null=True ,blank=True)
    NONLIVINGAREA_MEDI  = models.FloatField(null=True ,blank=True)
    TOTALAREA_MODE  = models.FloatField(null=True ,blank=True)
    OBS_30_CNT_SOCIAL_CIRCLE  = models.FloatField(null=True ,blank=True)
    DEF_30_CNT_SOCIAL_CIRCLE  = models.FloatField(null=True ,blank=True)
    OBS_60_CNT_SOCIAL_CIRCLE  = models.FloatField(null=True ,blank=True)
    DEF_60_CNT_SOCIAL_CIRCLE  = models.FloatField(null=True ,blank=True)
    DAYS_LAST_PHONE_CHANGE = models.IntegerField(null=True ,blank=True)
    FLAG_DOCUMENT_2 = models.IntegerField(null=True ,blank=True)
    FLAG_DOCUMENT_3 = models.IntegerField(null=True ,blank=True)
    FLAG_DOCUMENT_4 = models.IntegerField(null=True ,blank=True)
    FLAG_DOCUMENT_5 = models.IntegerField(null=True ,blank=True)
    FLAG_DOCUMENT_6 = models.IntegerField(null=True ,blank=True)
    FLAG_DOCUMENT_7 = models.IntegerField(null=True ,blank=True)
    FLAG_DOCUMENT_8 = models.IntegerField(null=True ,blank=True)
    FLAG_DOCUMENT_9 = models.IntegerField(null=True ,blank=True)
    FLAG_DOCUMENT_10 = models.IntegerField(null=True ,blank=True)
    FLAG_DOCUMENT_11 = models.IntegerField(null=True ,blank=True)
    FLAG_DOCUMENT_12 = models.IntegerField(null=True ,blank=True)
    FLAG_DOCUMENT_13 = models.IntegerField(null=True ,blank=True)
    FLAG_DOCUMENT_14 = models.IntegerField(null=True ,blank=True)
    FLAG_DOCUMENT_15 = models.IntegerField(null=True ,blank=True)
    FLAG_DOCUMENT_16 = models.IntegerField(null=True ,blank=True)
    FLAG_DOCUMENT_17 = models.IntegerField(null=True ,blank=True)
    FLAG_DOCUMENT_18 = models.IntegerField(null=True ,blank=True)
    FLAG_DOCUMENT_19 = models.IntegerField(null=True ,blank=True)
    FLAG_DOCUMENT_20 = models.IntegerField(null=True ,blank=True)
    FLAG_DOCUMENT_21 = models.IntegerField(null=True ,blank=True)
    AMT_REQ_CREDIT_BUREAU_HOUR  = models.FloatField(null=True ,blank=True)
    AMT_REQ_CREDIT_BUREAU_DAY  = models.FloatField(null=True ,blank=True)
    AMT_REQ_CREDIT_BUREAU_WEEK  = models.FloatField(null=True ,blank=True)
    AMT_REQ_CREDIT_BUREAU_MON  = models.FloatField(null=True ,blank=True)
    AMT_REQ_CREDIT_BUREAU_QRT  = models.FloatField(null=True ,blank=True)
    AMT_REQ_CREDIT_BUREAU_YEAR  = models.FloatField(null=True ,blank=True)
    OFFICER_ID = models.CharField(null=True ,blank=True,max_length=70)


class IncomeData(models.Model): 
    LOAN_ID = models.IntegerField(null=True ,blank=True)
    age =models.IntegerField(null=True ,blank=True)
    workclass =models.CharField(null=True ,blank=True,max_length=255)
    fnlwgt =models.IntegerField(null=True ,blank=True)
    education =models.CharField(null=True ,blank=True,max_length=255)
    education_num =models.IntegerField(null=True ,blank=True)
    marital_status =models.CharField(null=True ,blank=True,max_length=255)
    occupation =models.CharField(null=True ,blank=True,max_length=255)
    relationship =models.CharField(null=True ,blank=True,max_length=255)
    race =models.CharField(null=True ,blank=True,max_length=255)
    sex =models.CharField(null=True ,blank=True,max_length=255)
    capital_gain =models.IntegerField(null=True ,blank=True)
    capital_loss =models.IntegerField(null=True ,blank=True)
    hours_per_week =models.IntegerField(null=True ,blank=True)
    native_country =models.CharField(null=True ,blank=True,max_length=255)
    income =models.CharField(null=True ,blank=True,max_length=255)


class Country(models.Model): 
    name = models.CharField(max_length=200, default='zim')
    official_language = models.TextField(null=True ,blank=True)
    flag = models.ImageField(null=True ,blank=True, upload_to='static/images/countries/flags')
    longi = models.TextField(null=True ,blank=True)
    lat = models.TextField(null=True ,blank=True) 


